config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) {user.admin?} do
    get 'admin', to: 'admin#index'
    get 'admin/posts'
    get 'admin/comments'
    get 'admin/users'
    get 'admin/show_post/:id', to: "admin#show_post", as: 'admin_post'
  end
    get 'search', to: 'search#index'
    get 'users/profile'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get '/u/:id', to: 'users#profile', as: 'user'
  resources :posts do
    resources :comments
  end
get 'about', to: "pages#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
root "pages#home"
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
<% elsif alert %>
  <p class="alert"><%= alert %></p>
<%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Rails Blog", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li>
        <%= link_to "Blog", posts_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>          
        </li>        
      </ul>
      <ul class="navbar-nav">
        <%= render 'search/form' %>
        <%= render 'layouts/notifications' %>
        <%= render 'user/session_manager' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notification.html.erb
<li class="dropdown-item">
  <%= link_to notification.to_notification.message, notification.to_notification.url %>
</li>

app/views/layouts/_notifications.html.erb
<% if current_user %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <span class="badge rounded-pill bg-danger">
        <%= @unread.count >= 9 ? "9+" : @unread.count %> <i class="bi bi-suit-heart-fill"></i>
      </span>
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
      <% @unread.each do |notification| %>
        <%= render 'layouts/notification', notification: notification %>
      <% end %>
      <% if @read.count > 0 && @unread.count > 0 %>
        <li>
          <hr class="dropdown-divider">
        </li>
      <% elsif @read.count + @unread.count == 0 %>
        <li class="dropdown-item">
          No notifications yet.
        </li>
      <% end %>
      <% @read.each do |notification| %>
        <%= render 'layouts/notification', notification: notification %>
      <% end %>
    </ul>
  </li>
<% end %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar'%>
      <%= render 'layouts/alerts'%>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>